---
.travis.yml:
  user: "herculesteam"
  secure: "ctbh1VqtkZnqCWRa5YUONzS4LuJ3h36wOcn8pCyxNtdOcHNvbFYWiFaVIlgJXkkwFIRU7hnhpIXZ9bRCLqmvz3awVzc7baThgx2Asi5jkMlltXWIuCt8ZPHHpLNSEa0zHY88o7LUqTuvUCbG3EINYoA7o6ShBUV5vJ8UE6IesqU="
  before_install_pre:
    - "travis_retry ./.travis.sh"
  global_env:
    - AUGEAS_LENS_LIB=lib/augeas/lenses:spec/fixtures/augeas/lenses
Gemfile:
  required:
    ':development':
      - gem: coveralls
      - gem: ruby-augeas
spec/spec_helper.rb:
  puppet_core_modules:
    - sshkeys_core
